"""Multiple Hypothesis Testing report — Phase 3.11.

Combines DSR, PBO, and MHT corrections into a single
:class:`HypothesisTestingReport` with markdown rendering.

Decision rule per ADR-0004 Step 6:
- DSR > 0.95 (significant after deflation for n_trials)
- PBO < 0.10 (strong evidence of genuine edge, not overfitting)
- If multiple strategies: MHT-corrected p-value < α

Reference
---------
- Bailey & López de Prado (2014). "The Deflated Sharpe Ratio." JPM.
- Bailey et al. (2014). "Probability of Backtest Overfitting." JCF.
- Holm (1979). "Sequential rejective test procedure." Scand. J. Stat.
- Benjamini & Hochberg (1995). "Controlling the FDR." JRSS B.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from features.hypothesis.dsr import DSRResult
from features.hypothesis.pbo import PBOResult

# ADR-0004 thresholds
_DSR_THRESHOLD: float = 0.95
_PBO_THRESHOLD: float = 0.10


@dataclass(frozen=True)
class FeatureDecision:
    """Statistical decision for a single feature/strategy."""

    feature_name: str
    sharpe_raw: float
    psr: float
    dsr: float
    min_trl: int
    n_trials: int
    n_obs: int
    p_value_raw: float
    p_value_holm: float | None  # None if single strategy
    p_value_bh: float | None
    decision: Literal["pass", "fail"]
    fail_reasons: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class HypothesisTestingReport:
    """Aggregate report combining DSR, PBO, and MHT results.

    Generated by :func:`build_report`.
    """

    feature_decisions: list[FeatureDecision]
    pbo_result: PBOResult | None  # None if < 2 features
    mht_correction: Literal["holm", "bh", "none"]
    alpha: float
    n_features: int
    n_pass: int
    n_fail: int

    def to_markdown(self) -> str:
        """Render the report as a deterministic Markdown string."""
        lines: list[str] = []
        lines.append("# Phase 3.11 — Multiple Hypothesis Testing Report")
        lines.append("")
        lines.append("## Configuration")
        lines.append("")
        lines.append(f"- **Number of features tested**: {self.n_features}")
        lines.append(f"- **MHT correction**: {self.mht_correction}")
        lines.append(f"- **Significance level (α)**: {self.alpha}")
        lines.append(f"- **DSR threshold**: {_DSR_THRESHOLD}")
        lines.append(f"- **PBO threshold**: {_PBO_THRESHOLD}")
        lines.append("")

        # Per-feature table
        lines.append("## Per-Feature Statistical Signatures")
        lines.append("")
        header = "| Feature | Sharpe | PSR | DSR | Min-TRL | p_raw | p_holm | p_BH | Decision |"
        sep = "|---|---|---|---|---|---|---|---|---|"
        lines.append(header)
        lines.append(sep)
        for fd in self.feature_decisions:
            p_holm = f"{fd.p_value_holm:.4f}" if fd.p_value_holm is not None else "—"
            p_bh = f"{fd.p_value_bh:.4f}" if fd.p_value_bh is not None else "—"
            dec = "PASS" if fd.decision == "pass" else "FAIL"
            lines.append(
                f"| {fd.feature_name} | {fd.sharpe_raw:.3f} | "
                f"{fd.psr:.3f} | {fd.dsr:.3f} | {fd.min_trl} | "
                f"{fd.p_value_raw:.4f} | {p_holm} | {p_bh} | {dec} |"
            )
        lines.append("")

        # PBO section
        if self.pbo_result is not None:
            lines.append("## PBO Results")
            lines.append("")
            lines.append(
                f"- **PBO**: {self.pbo_result.pbo:.4f} "
                f"({'OVERFIT' if self.pbo_result.is_overfit else 'OK'})"
            )
            lines.append(
                f"- **Passes ADR-0004 (PBO < {_PBO_THRESHOLD})**: "
                f"{'Yes' if self.pbo_result.passes_adr0004 else 'No'}"
            )
            lines.append(f"- **Number of folds**: {self.pbo_result.n_folds}")
            lines.append(f"- **Number of features**: {self.pbo_result.n_features}")
            lines.append("")

        # Decision summary
        lines.append("## Decision Summary")
        lines.append("")
        lines.append(
            f"- **{self.n_pass} / {self.n_features}** features pass "
            f"after MHT correction ({self.mht_correction} at α={self.alpha})"
        )
        lines.append(f"- **{self.n_fail} / {self.n_features}** correctly rejected")
        lines.append("")

        # Fail reasons
        failed = [fd for fd in self.feature_decisions if fd.decision == "fail"]
        if failed:
            lines.append("## Rejection Details")
            lines.append("")
            for fd in failed:
                reasons = "; ".join(fd.fail_reasons) if fd.fail_reasons else "—"
                lines.append(f"- **{fd.feature_name}**: {reasons}")
            lines.append("")

        # References
        lines.append("## References")
        lines.append("")
        lines.append(
            '- Bailey & López de Prado (2014). "The Deflated Sharpe Ratio." *JPM* 40(5), 94-107.'
        )
        lines.append(
            "- Bailey, Borwein, López de Prado, Zhu (2014). "
            '"Probability of Backtest Overfitting." *JCF*.'
        )
        lines.append(
            '- Holm (1979). "Sequential rejective test procedure." *Scand. J. Stat.* 6:65-70.'
        )
        lines.append(
            '- Benjamini & Hochberg (1995). "Controlling the FDR." *JRSS B* 57(1):289-300.'
        )
        lines.append("")
        return "\n".join(lines)


def build_report(
    dsr_results: list[DSRResult],
    pbo_result: PBOResult | None = None,
    *,
    p_values_holm: dict[str, float] | None = None,
    p_values_bh: dict[str, float] | None = None,
    p_values_raw: dict[str, float] | None = None,
    alpha: float = 0.05,
    mht_correction: Literal["holm", "bh", "none"] = "holm",
) -> HypothesisTestingReport:
    """Build the hypothesis testing report from component results.

    Parameters
    ----------
    dsr_results : list[DSRResult]
        Per-feature DSR results from :class:`DeflatedSharpeCalculator`.
    pbo_result : PBOResult | None
        PBO result from :class:`PBOCalculator`.  ``None`` when < 2 features.
    p_values_holm : dict | None
        ``{feature: holm_adjusted_p}`` from :func:`holm_bonferroni`.
    p_values_bh : dict | None
        ``{feature: bh_adjusted_p}`` from :func:`benjamini_hochberg`.
    p_values_raw : dict | None
        ``{feature: raw_p}`` — the unadjusted p-values.
    alpha : float
        Significance level.
    mht_correction : str
        Which correction drives the decision: ``"holm"``, ``"bh"``, or ``"none"``.

    Returns
    -------
    HypothesisTestingReport

    Raises
    ------
    ValueError
        If MHT correction is requested for multiple features but the
        corresponding p-values dict is missing.  Pass
        ``mht_correction="none"`` to explicitly skip MHT.
    """
    # Validate MHT contract — prevent silent skip
    if mht_correction == "holm" and len(dsr_results) > 1 and p_values_holm is None:
        msg = (
            "mht_correction='holm' requires p_values_holm dict when "
            "evaluating multiple features. Pass mht_correction='none' "
            "explicitly to skip MHT correction."
        )
        raise ValueError(msg)
    if mht_correction == "bh" and len(dsr_results) > 1 and p_values_bh is None:
        msg = (
            "mht_correction='bh' requires p_values_bh dict when "
            "evaluating multiple features. Pass mht_correction='none' "
            "explicitly to skip MHT correction."
        )
        raise ValueError(msg)

    decisions: list[FeatureDecision] = []

    for dsr in dsr_results:
        name = dsr.feature_name
        raw_p = p_values_raw.get(name, 1.0 - dsr.dsr) if p_values_raw else 1.0 - dsr.dsr
        holm_p = p_values_holm.get(name) if p_values_holm else None
        bh_p = p_values_bh.get(name) if p_values_bh else None

        fail_reasons: list[str] = []

        # DSR gate
        if dsr.dsr < _DSR_THRESHOLD:
            fail_reasons.append(f"DSR {dsr.dsr:.3f} < {_DSR_THRESHOLD}")

        # PBO gate (applies to all features if computed)
        if pbo_result is not None and pbo_result.pbo >= _PBO_THRESHOLD:
            fail_reasons.append(f"PBO {pbo_result.pbo:.3f} >= {_PBO_THRESHOLD}")

        # MHT gate
        if mht_correction == "holm" and holm_p is not None and holm_p > alpha:
            fail_reasons.append(f"p_holm {holm_p:.4f} > α={alpha}")
        elif mht_correction == "bh" and bh_p is not None and bh_p > alpha:
            fail_reasons.append(f"p_bh {bh_p:.4f} > α={alpha}")

        decision: Literal["pass", "fail"] = "pass" if not fail_reasons else "fail"

        decisions.append(
            FeatureDecision(
                feature_name=name,
                sharpe_raw=dsr.sharpe_ratio,
                psr=dsr.psr,
                dsr=dsr.dsr,
                min_trl=dsr.min_trl,
                n_trials=dsr.n_trials,
                n_obs=dsr.n_obs,
                p_value_raw=raw_p,
                p_value_holm=holm_p,
                p_value_bh=bh_p,
                decision=decision,
                fail_reasons=fail_reasons,
            )
        )

    n_pass = sum(1 for d in decisions if d.decision == "pass")
    n_fail = sum(1 for d in decisions if d.decision == "fail")

    return HypothesisTestingReport(
        feature_decisions=decisions,
        pbo_result=pbo_result,
        mht_correction=mht_correction,
        alpha=alpha,
        n_features=len(decisions),
        n_pass=n_pass,
        n_fail=n_fail,
    )
